# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded CipherUtil 1.0 [list source [file join $dir ./library/utils.tcl]]
package ifneeded Crithm 1.0 [list source [file join $dir ./library/crithm.tcl]]
package ifneeded Crithm_gui 1.0 [list source [file join $dir ./library/crithm_gui.tcl]]
package ifneeded Dictionary 1.0 [list source [file join $dir ./library/dictionary.tcl]]
package ifneeded GeneticPerm 1.0 [list source [file join $dir ./library/geneticPerm.tcl]]
package ifneeded Hillclimb 1.0 [list source [file join $dir ./library/hillclimbCiphers.tcl]]\n[list source [file join $dir ./library/hillclimb.tcl]]
package ifneeded K3Board 1.0 [list source [file join $dir ./library/k3board.tcl]]
package ifneeded PatWord 1.0 [list source [file join $dir ./library/patword.tcl]]
package ifneeded PatWordUI 1.0 [list source [file join $dir ./library/patwordui.tcl]]
package ifneeded Scoredata 1.0 [list source [file join $dir ./library/scoredata.tcl]]
package ifneeded Scoretypes 1.0 [list source [file join $dir ./library/scoretypes.tcl]]
package ifneeded cipher 1.6.2 [list load [file join $dir libcipher1.6.2.so]]
package ifneeded ciphertool 1.3 [list source [file join $dir ./library/aristocrat.tcl]]\n[list source [file join $dir ./library/baconian.tcl]]\n[list source [file join $dir ./library/beaufort.tcl]]\n[list source [file join $dir ./library/bifid.tcl]]\n[list source [file join $dir ./library/cadenus.tcl]]\n[list source [file join $dir ./library/columnar.tcl]]\n[list source [file join $dir ./library/ctool_inputs.tcl]]\n[list source [file join $dir ./library/ctool.tcl]]\n[list source [file join $dir ./library/fmorse.tcl]]\n[list source [file join $dir ./library/grandpre.tcl]]\n[list source [file join $dir ./library/grille.tcl]]\n[list source [file join $dir ./library/gronsfeld.tcl]]\n[list source [file join $dir ./library/homophonic.tcl]]\n[list source [file join $dir ./library/keyphrase.tcl]]\n[list source [file join $dir ./library/morbit.tcl]]\n[list source [file join $dir ./library/myszcowski.tcl]]\n[list source [file join $dir ./library/nitrans.tcl]]\n[list source [file join $dir ./library/pollux.tcl]]\n[list source [file join $dir ./library/porta.tcl]]\n[list source [file join $dir ./library/railfence.tcl]]\n[list source [file join $dir ./library/swagman.tcl]]\n[list source [file join $dir ./library/variant.tcl]]\n[list source [file join $dir ./library/vigenere.tcl]]
