#!/bin/sh

cipherfile=$1

for type in vigenere variant beaufort ; do
    for encoding in vigenere variant beaufort ; do
	for period in 4 5 6 7 8 9 10 11 12 13 14 15 ; do
	    for progIndex in 1 2 3 4 5 6 7; do
		echo "Trying ${type} ${encoding} ${period} ${progIndex}"
		/home/wart/src/ciphers/ciphertool/progs/progkeysol ${cipherfile} ${type} ${encoding} ${period} ${progIndex} > $cipherfile.progsol.${period}-${type}-${encoding}-${progIndex}
	    done
	done
    done
done
