#!/bin/sh
# \
exec tclsh "$0" ${1+"$@"}

# dosolver --
#
#	Driver for the aristocrat "solver" program.  Iterates through
#	various command line options until a solution is found.
#
# RCS: @(#) $Id: vigenere.tcl,v 1.2 2004/09/08 14:42:09 wart Exp $
#
# Copyright (C) 2003  Mike Thomas <wart@kobold.org>
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

package require cmdline

set options [list \
    [list update "Indicate if the dictionary should be updated with the common words."] \
]

if {[catch {
    foreach {var val} [::cmdline::getoptions argv $options] {
	set $var $val
    }
} msg]} {
    puts stderr $msg
    exit 1
}

set fileList $argv
set updateFlag {}
if {$update} {
    set updateFlag "-u"
}

foreach file $fileList {
    set outfilename $file.solauto
    set outChanId [open $outfilename w]
    set foundSolution 0
    for {set threshhold 0} \
	    {$threshhold < 5 && !$foundSolution} \
	    {incr threshhold} {

	set output {}
	set updateFlag {}
	if {$update && $threshhold == 0} {
	    set updateFlag "-u"
	}
	set progChan [open "|solver -f $file -t $threshhold $updateFlag -o -" r]
	puts "$file [string repeat "  " $threshhold]($threshhold)"
	while {![eof $progChan]} {
	    gets $progChan line
	    # Ignore empty lines.
	    if {$line != ""} {
		puts $outChanId $line
		set foundSolution 1
	    }
	}
	close $progChan
    }
    close $outChanId
}
