#!/bin/sh
# \
exec wish "$0" ${1+"$@"}

# k3board --
#
#	A GUI tool for manipulating k3 alphabet fragments.
#
# RCS: @(#) $Id: vigenere.tcl,v 1.2 2004/09/08 14:42:09 wart Exp $
#
# Copyright (C) 2002  Mike Thomas <wart@kobold.org>
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

package require cipher
package require CipherUtil
package require K3Board

# Command line processing

if {[llength $argv] > 1} {
    puts stderr "Usage:  $argv0 ?file?"
    exit 1
}

set filename [lindex $argv 0]
set fragmentList {}

option add *Entry*background	white
option add *Text*background	white
option add *Text.font		-adobe-courier-bold-r-normal--14-140-75-75-m-90-iso8859-1

frame	.mbar -relief raised -bd 2
menubutton .mbar.file -text File -menu .mbar.file.menu
menu	.mbar.file.menu -tearoff 0
.mbar.file.menu add command -label "New" -command {K3Board::loadFragments [tk_getOpenFile -title "Open new cipher"] fragmentList}
.mbar.file.menu add command -label "Exit" -command exit

pack	.mbar.file -anchor w -side left
pack	.mbar -fill x

set K3Board::viewWidget  [text .fragview -width 80 -height 5 -bg white]
set K3Board::manipWidget [text .fragmanip -width 80 -height 13 -bg white]

pack	.fragview .fragmanip -fill x

if {$filename != ""} {
    K3Board::loadFragments $filename fragmentList
}
