#!/bin/sh
# \
exec tclsh "$0" ${1+"$@"}

# keysearch --
#
#	Search for keywords from a K1 keyed alphabet.
#
# RCS: @(#) $Id: keysearch,v 1.4 2008/03/16 23:47:29 wart Exp $
#
# Copyright (C) 2001  Mike Thomas <wart@kobold.org>
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

package require cipher
package require Dictionary

if {[llength $argv] != 1} {
    puts stderr "Usage:  $argv0 key"
}

set key [lindex $argv 0]

foreach wordLength [Dictionary::availableLengths] {
    foreach keyword [Dictionary::lookupByLength $wordLength] {
	if {[catch {set testKey [key generate $keyword]}]} {
	    #puts "Skipping invalid keyword $keyword"
	} elseif {[key match $key $testKey]} {
	    puts stdout "$keyword  ($testKey)"
	}
    }
}
