#!/bin/sh
# \
exec tclsh "$0" ${1+"$@"}

# rot --
#
#	Perform caesar shifts on some ciphertext.
#
# RCS: @(#) $Id: rot,v 1.5 2008/03/05 03:54:59 wart Exp $
#
# Copyright (C) 2003  Mike Thomas <wart@kobold.org>
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

package require cmdline
package require cipher
package require CipherUtil

# Command line processing

set options [list \
    [list file.arg "-" "The name of the input cipher file"] \
    [list shift.arg "0" "Amount of shift.  This can be specified as a Tcl list to test multiple shifts."]]

if {[catch {
    foreach {var val} [::cmdline::getoptions argv $options] {
	set $var $val
    }
} msg]} {
    puts stderr $msg
    exit 1
}

# Command line validation

if {$shift == 0} {
    set shift {}
    for {set i 0} {$i < 26} {incr i} {
	lappend shift $i
    }
}

if {$argv == ""} {
    set ct [CipherUtil::readCiphertext $file]
} else {
    set ct $argv
}

set cipher [cipher create caesar -ct $ct]

foreach val $shift {
    $cipher configure -shift $val
    puts "[format %2d $val]: [$cipher cget -pt]"
}
